name: Build & Deploy (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/hexo-blog

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-server:
    runs-on: ubuntu-latest
    needs: build-image
    if: ${{ success() }} # 若需按条件控制，可改为: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy over SSH (pull & recreate)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}        # 在仓库 Settings -> Secrets 添加
          username: ${{ secrets.SSH_USER }}    # 如: root
          key: ${{ secrets.SSH_KEY }}          # 私钥内容
          # port: ${{ secrets.SSH_PORT }}      # 可选，若不设置使用 22
          script: |
            set -e
            IMAGE=ghcr.io/${{ github.repository_owner }}/hexo-blog:latest
            DEPLOY_PATH=${DEPLOY_PATH:-/opt/hexo}
            mkdir -p "$DEPLOY_PATH"
            cd "$DEPLOY_PATH"
            docker pull $IMAGE
            docker compose up -d --remove-orphans blog
            docker image prune -f
